defaults:
  - hydra: default
  - logger: mlflow
  - /data/datasets@data.train: prostate_cancer/train
  - /data/datasets@data.val: prostate_cancer/val
  - /data/datasets@data.test: prostate_cancer/test
  - /ciao/segmentation: superpixel
  - /ciao/obfuscation: blur
  - _self_

seed: ${random_seed:}
mode: explain
variant: prostate # prostate or colorectal

ciao:
  explainer_params:
    eta: 0.03
    radius_range: [1]
    adaptive_eta: true
    target_class: null
    use_fallback_groups: true
    max_group_size_ratio: 0.02
    max_display_groups: 30

data:
  batch_size: 1 # CIAO processes single images
  num_workers: 4

explanation:
  num_images: 5 # Number of images to explain
  output_dir: ./explanations
  save_visualizations: true
  save_heatmaps: true

metadata:
  experiment_name: Explainability
  run_name: "CIAO_${variant}_${ciao.segmentation._target_}_${ciao.obfuscation._target_}"
  description: "CIAO explanations for medical images"
  hyperparams:
    eta: ${ciao.explainer_params.eta}
    batch_size: ${data.batch_size}
    segmentation: ${ciao.segmentation._target_}
    obfuscation: ${ciao.obfuscation._target_}
